services:
  - type: web
    name: ecommerce-web
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn ecommerce.wsgi:application --bind 0.0.0.0:8000
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: ecommerce.settings
      - key: DATABASE_URL
        value: postgresql://ecommerce_1vgf_user:Gljm5RZVAB2yKEAEVApcVdIjUUzF2usW@dpg-d00trg3uibrs73eqsbo0-a.virginia-postgres.render.com/ecommerce_1vgf
      - key: DJANGO_SECRET_KEY
        fromSecret: 'django-insecure-(wlxd-4*159by$$_f+r)ugq5p)^!z2h38b7_$or^ubln-&$a@z'
    autoDeploy: true
    plan: starter
